sources:
  - name: ScoopsSearch
    handler:
      graphql:
        endpoint: http://localhost:8080/graphql/ScoopsSearch
        baseUrl: http://localhost:8080/
        operationHeaders:
          user: "{env.user}"
          x-zisession: "{env.x-zisession}"
          x-ziid: "{env.x-ziid}"
          x-ziaccesstoken: "{env.x-ziaccesstoken}"

  - name: FacetsSearch 
    handler:
      graphql:
        endpoint: http://localhost:8080/graphql/facets
        baseUrl: http://localhost:8080/
        operationHeaders:
          user: "{env.user}"
          x-zisession: "{env.x-zisession}"
          x-ziid: "{env.x-ziid}"
          x-ziaccesstoken: "{env.x-ziaccesstoken}"

additionalEnvelopPlugins: './envelopPlugins'